### PR TITLE
Fix/addressbook

### LINKED ISSUE #196: Address book management
Currently, new addresses and their labels are automatically saved to a local state. When addresses are found to correspond to a domain, the domain is used in lieu of a label. Right now, there are ways to delete saved addresses (simply by clicking X when addresses show up), but no way to edit them. Moreover, addresses of deleted wallets are not automatically removed. The result is saved addresses blow up very quickly, and after using the wallets for a while, the users generally see a bunch of irrelevant addresses at first when they click the address input box.  

We should allow addresses to be edited, by adding an edit button, in addition to existing delete button (X). The edit prompt could be a popover, or simply leading the user to a dedicated page where all saved addresses are listed and can be managed. As usual, modal should not be used.
 
References for starting point:
https://github.com/polymorpher/one-wallet/blob/master/code/client/src/components/AddressInput.jsx

### PR DESCRIPTION
**Pull request by cylim**
@polymorpher 
- Added auto remove wallet address in knownAddress
- Added Edit Address Label page for other known address

closes #196

### CODE REVIEW

**Comment by polymorpher** [comment]
thanks, I will try after wrapping up things with a deadline, later today

File: code/client/src/pages/Contacts/AddressDetail.jsx [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+          <Label ultraWide>
+            <Hint>Address</Hint>
+          </Label>
+          <WalletAddress showLabel address={contact?.address} shorten />
+        </Space>
+        <Space align="baseline" size="large">
+          <Label ultraWide>
+            <Hint>Domain</Hint>
+          </Label>
+          <InputBox
```
Comment (polymorpher) [inline code/client/src/pages/Contacts/AddressDetail.jsx:83]: Let's use label since it is immutable

File: code/client/src/components/AddressInput.jsx [hunk 2]
```diff
@@ -302,20 +305,27 @@ const AddressInput = ({ setAddressCallback, currentWallet, addressValue, extraSe
               </Button>
             </Tooltip>
           </Col>
-          <Col span={4}>
+          <Col span={5}>
             {
-            displayDeleteButton
-              ? (
-                <Button
+            displayActionButton
```
Comment (polymorpher) [inline code/client/src/components/AddressInput.jsx:310]: overflowing on mobile

**Comment by polymorpher** [comment]
Overall looks good. I will merge it and do the minor fixes. I will also add you as collaborator in the repository so it would be easier to edit and fix in the future

**Comment by polymorpher** [comment]
Another thing: let's make sure the code is formatted by eslint
